image: maven:3.5.0-jdk-8

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y openjfx
          - mvn -B verify # -B batch mode makes Maven less verbose